In [9]:
import numpy as np
import pandas as pd
from IPython.display import display

df1 = pd.read_csv("salary_test_data_male.csv")
df2 = pd.read_csv("salary_test_data_female.csv")

merged = pd.concat([df1,df2])

for race in merged["race"].unique():
  new_df = merged[merged["race"]==race]
  new_df.to_csv(f"salay_data_{race}.csv")

In [8]:
test_df_aie = pd.read_csv("/content/salay_data_Amer-Indian-Eskimo.csv")
test_df_api = pd.read_csv("/content/salay_data_Asian-Pac-Islander.csv")
test_df_blk = pd.read_csv("/content/salay_data_Black.csv")
test_df_other = pd.read_csv("/content/salay_data_Other.csv")
test_df_white = pd.read_csv("/content/salay_data_White.csv")


In [22]:
feature_columns = ["age","education-num","marital-status",
                                "occupation","hours-per-week",
                                "native-country","y"]

aie_data = test_df_aie[feature_columns]
api_data = test_df_api[feature_columns]
blk_data = test_df_blk[feature_columns]
other_data = test_df_other[feature_columns]
white_data = test_df_white[feature_columns]

display(aie_data.head())
display(api_data.head())
display(blk_data.head())
display(other_data.head())
display(white_data.head())

age  education-num      marital-status         occupation  hours-per-week  \
0   34             14       Never-married      Other-service              40   
1   33              9  Married-civ-spouse  Handlers-cleaners              40   
2   35              5  Married-civ-spouse       Craft-repair              96   
3   44             11            Divorced  Machine-op-inspct              40   
4   31              1       Never-married  Handlers-cleaners              25   

  native-country      y  
0  United-States  <=50K  
1  United-States  <=50K  
2  United-States  <=50K  
3  United-States  <=50K  
4  United-States  <=50K

age  education-num      marital-status         occupation  hours-per-week  \
0   34             13  Married-civ-spouse       Adm-clerical              40   
1   51              9  Married-civ-spouse              Sales              84   
2   37              9           Separated  Machine-op-inspct              60   
3   45             13  Married-civ-spouse    Exec-managerial              45   
4   36             14  Married-civ-spouse    Exec-managerial              45   

  native-country      y  
0    Philippines  <=50K  
1        Vietnam  <=50K  
2  United-States  <=50K  
3          Japan   >50K  
4          India  <=50K

age  education-num      marital-status         occupation  hours-per-week  \
0   25              7       Never-married  Machine-op-inspct              40   
1   44             10  Married-civ-spouse  Machine-op-inspct              40   
2   23              9           Separated  Machine-op-inspct              54   
3   46             10  Married-civ-spouse    Exec-managerial              38   
4   39              9            Divorced  Handlers-cleaners              40   

  native-country      y  
0  United-States  <=50K  
1  United-States   >50K  
2  United-States  <=50K  
3  United-States   >50K  
4  United-States  <=50K

age  education-num      marital-status       occupation  hours-per-week  \
0   46             10  Married-civ-spouse     Craft-repair              40   
1   21              9       Never-married    Other-service              20   
2   21             10       Never-married     Adm-clerical              40   
3   64              2  Married-civ-spouse  Farming-fishing              45   
4   35              9       Never-married     Craft-repair              40   

       native-country      y  
0  Dominican-Republic  <=50K  
1       United-States  <=50K  
2       United-States  <=50K  
3            Columbia  <=50K  
4         Puerto-Rico  <=50K

age  education-num      marital-status       occupation  hours-per-week  \
0   38              9  Married-civ-spouse  Farming-fishing              50   
1   28             12  Married-civ-spouse  Protective-serv              40   
2   34              6       Never-married    Other-service              30   
3   63             15  Married-civ-spouse   Prof-specialty              32   
4   55              4  Married-civ-spouse     Craft-repair              10   

  native-country      y  
0  United-States  <=50K  
1  United-States   >50K  
2  United-States  <=50K  
3  United-States   >50K  
4  United-States  <=50K

In [23]:
from re import X
def featurize(df):
    X = df[['age','education-num','hours-per-week']]
    print (X)
    X['marital-status'] = [1 if x=='Married-civ-spouse' else 0 for x in df['marital-status']]
    X['native-country'] = [1 if x=='United-States' else 0 for x in df['native-country']]

    occ_groups = {
        'Priv-house-serv':0,'Other-service':0,'Handlers-cleaners':0,
        'Farming-fishing':1,'Machine-op-inspct':1,'Adm-clerical':1,
        'Transport-moving':2,'Craft-repair':2,'Sales':2,
        'Armed-Forces':3,'Tech-support':3,'Protective-serv':3,
        'Prof-specialty':4,'Exec-managerial':4,'?':0}

    X['occupation'] = [occ_groups.get(x.strip()) for x in df['occupation']]
    return X

# we also convery Y into 0/1 format

X_test_aie = featurize(aie_data)
y_actual_aie = [1 if y == '>50K' else 0 for y in aie_data['y']]
X_test_api = featurize(api_data)
y_actual_api = [1 if y == '>50K' else 0 for y in api_data['y']]
X_test_blk = featurize(blk_data)
y_actual_blk = [1 if y == '>50K' else 0 for y in blk_data['y']]
X_test_other = featurize(other_data)
y_actual_other = [1 if y == '>50K' else 0 for y in other_data['y']]
X_test_white = featurize(white_data)
y_actual_white = [1 if y == '>50K' else 0 for y in white_data['y']]

display(X_test_aie.head())
display(X_test_api.head())
display(X_test_blk.head())
display(X_test_other.head())
display(X_test_white.head())

     age  education-num  hours-per-week
0     34             14              40
1     33              9              40
2     35              5              96
3     44             11              40
4     31              1              25
..   ...            ...             ...
144   17              7              15
145   38             10              40
146   51             10              35
147   29              9              40
148   43             10              36

[149 rows x 3 columns]
     age  education-num  hours-per-week
0     34             13              40
1     51              9              84
2     37              9              60
3     45             13              45
4     36             14              45
..   ...            ...             ...
403   21             10              15
404   35             12              40
405   57             11              40
406   29              9              45
407   18              9              15

[408 rows x 3 c

<ipython-input-23-7ad578e5e3ed>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['marital-status'] = [1 if x=='Married-civ-spouse' else 0 for x in df['marital-status']]
<ipython-input-23-7ad578e5e3ed>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['native-country'] = [1 if x=='United-States' else 0 for x in df['native-country']]
<ipython-input-23-7ad578e5e3ed>:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value

age  education-num  hours-per-week  marital-status  native-country  \
0   34             14              40               0               1   
1   33              9              40               1               1   
2   35              5              96               1               1   
3   44             11              40               0               1   
4   31              1              25               0               1   

   occupation  
0           0  
1           0  
2           2  
3           1  
4           0

age  education-num  hours-per-week  marital-status  native-country  \
0   34             13              40               1               0   
1   51              9              84               1               0   
2   37              9              60               0               1   
3   45             13              45               1               0   
4   36             14              45               1               0   

   occupation  
0           1  
1           2  
2           1  
3           4  
4           4

age  education-num  hours-per-week  marital-status  native-country  \
0   25              7              40               0               1   
1   44             10              40               1               1   
2   23              9              54               0               1   
3   46             10              38               1               1   
4   39              9              40               0               1   

   occupation  
0           1  
1           1  
2           1  
3           4  
4           0

age  education-num  hours-per-week  marital-status  native-country  \
0   46             10              40               1               0   
1   21              9              20               0               1   
2   21             10              40               0               1   
3   64              2              45               1               0   
4   35              9              40               0               0   

   occupation  
0           2  
1           0  
2           1  
3           1  
4           2

age  education-num  hours-per-week  marital-status  native-country  \
0   38              9              50               1               1   
1   28             12              40               1               1   
2   34              6              30               0               1   
3   63             15              32               1               1   
4   55              4              10               1               1   

   occupation  
0           1  
1           3  
2           0  
3           4  
4           2

In [24]:
import pickle
from sklearn.metrics import accuracy_score

model_file = open("salary_classifier.model","rb")
model = pickle.load(model_file)

y_predicted_aie = model.predict(X_test_aie)
y_predicted_api = model.predict(X_test_api)
y_predicted_blk = model.predict(X_test_blk)
y_predicted_other = model.predict(X_test_other)
y_predicted_white = model.predict(X_test_white)

print(y_predicted_aie[:5])
print(y_predicted_api[:5])
print(y_predicted_blk[:5])
print(y_predicted_other[:5])
print(y_predicted_white[:5])

[0 0 0 0 0]
[1 1 0 1 1]
[0 0 0 1 0]
[0 0 0 1 0]
[1 0 0 1 0]


In [26]:
from sklearn.metrics import classification_report

print ("Printing classification report for Amer-Indian-Eskimo:")
print(classification_report(y_actual_aie,y_predicted_aie))

print ("Printing classification report for Asian-Pac-Islander:")
print(classification_report(y_actual_api,y_predicted_api))

print ("Printing classification report for Black:")
print(classification_report(y_actual_blk,y_predicted_blk))

print ("Printing classification report for Other:")
print(classification_report(y_actual_other,y_predicted_other))

print ("Printing classification report for White:")
print(classification_report(y_actual_white,y_predicted_white))

Printing classification report for Amer-Indian-Eskimo:
              precision    recall  f1-score   support

           0       0.93      0.88      0.91       130
           1       0.40      0.53      0.45        19

    accuracy                           0.84       149
   macro avg       0.66      0.71      0.68       149
weighted avg       0.86      0.84      0.85       149

Printing classification report for Asian-Pac-Islander:
              precision    recall  f1-score   support

           0       0.82      0.86      0.84       287
           1       0.64      0.56      0.60       121

    accuracy                           0.77       408
   macro avg       0.73      0.71      0.72       408
weighted avg       0.77      0.77      0.77       408

Printing classification report for Black:
              precision    recall  f1-score   support

           0       0.94      0.92      0.93      1243
           1       0.48      0.55      0.51       168

    accuracy                  

The "Other" group has the lowest f1 score and has fewer samples which would be potential bias. The "Other" and "Amer-Indian-Eskimo" have significantly lower f1 scores indicating potential underrepresentation. Lower precision and recall means that the models may incorrectly predict positive cases.